version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    ports:
      - '5050:8080'
      - '5443:8443'
      - '50000:50000'
    volumes:
      - './data:/var/jenkins_home'
      - '/data/dev/workspace:/workspace'
      - '/home/aparedes/.m2:/m2'
